# Generated by Django 3.2.6 on 2023-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_post_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
