# Generated by Django 3.2.6 on 2023-09-28 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='finished_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='読み終わった日'),
        ),
    ]
